spring.application.name=webshop-template-backend
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=604800000

stripe.api-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=http://localhost:3000/checkout/success
stripe.cancel-url=http://localhost:3000/checkout/cancel
