apiVersion: v1
kind: ConfigMap
metadata:
  name: webshop-backend-config
  labels:
    app: webshop-backend
data:
  SPRING_PROFILES_ACTIVE: "prod"
  FRONTEND_URL: "https://webshop-demo.oskott.com"
  MAIL_FROM: "oskar.ott@icloud.com"
